# Generated by Django 3.0.8 on 2020-07-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Topic_Name', models.CharField(max_length=20)),
                ('Content', models.CharField(max_length=1000)),
            ],
        ),
    ]
