# Generated by Django 3.0.8 on 2020-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulidingSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddev',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
