# Generated by Django 3.0.8 on 2020-07-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulidingSite', '0002_auto_20200727_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddev',
            old_name='Content',
            new_name='Skills',
        ),
        migrations.RenameField(
            model_name='adddev',
            old_name='Topic_Name',
            new_name='Tool',
        ),
    ]
